name: rocker-with-v8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: "rocker with V8 & curl"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: check repo
      uses: actions/checkout@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
