name: rocker-with-v8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    name: "rocker with V8 & curl"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: check repo
      uses: actions/checkout@v3

    
    - name: Login to Github container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dmunoztord/rocker-with-v8
